/// Flutter icons PetitsIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PetitsIcons
///      fonts:
///       - asset: fonts/PetitsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PetitsIcons {
  PetitsIcons._();

  static const _kFontFam = 'PetitsIcons';

  static const IconData sad = const IconData(0xe800, fontFamily: _kFontFam);
}
